compute_environment: LOCAL_MACHINE
deepspeed_config:
 gradient_clipping: "auto"
 offload_optimizer_device: none
 offload_param_device: none
 zero3_init_flag: true
 zero_stage: 1
 train_micro_batch_size_per_gpu: "auto"
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 2
use_cpu: false