# Model
model_name_or_path: "./bge-reranker-m3-base"
model_type: "bert_encoder"
num_labels: 1 # binary classification


# Dataset
train_dataset: "../../../example_data/t2rank_100.jsonl"
val_dataset: "../../../example_data/t2rank_100.small.jsonl"
max_label: 1
min_label: 0
max_len: 512 
query_format: "{}"
document_format: "{}"


# Training
output_dir: "./output/t2ranking_100_example"
save_on_epoch_end: 1
num_max_checkpoints: 5


## Hyperparameters
loss_type: "point_ce"  # "point_ce" or "point_mse"
epochs: 2
lr: 5e-5
batch_size: 96
seed: 666
warmup_proportion: 0.1
gradient_accumulation_steps: 1
mixed_precision: fp16 

## Logging
log_interval: 10
log_with: "wandb" # "wandb" or "tensorboard"



